version: v1
name: data-product-generator
type: service
service:
  replicas: 1
  servicePort: 3000
  ingress:
    enabled: true
    noAuthentication: true
    path: /data-product-generator
    stripPath: false
  stack: container
  compute: runnable-default
  envs:
    LOG_LEVEL: info
    NEXT_PUBLIC_BASE_PATH: /data-product-generator
  stackSpec:
    image: tmdcio/data-product-generator-production:1.6-dev
    imagePullSecret: modern-docker-secret-v1
    command:
      - node
    arguments:
      - server.js