name: transaction-bundle
version: v1beta
type: bundle
tags:
  - Tier.Gold
description: The purpose of the bundle is to deploy the resources of the transaction Data Product, making it available for consumption in transaction.
layer: "user"
bundle:
  resources:
    - id: transaction-pipeline
      file: 2.2-transaction/deploy/pipeline.yaml
      workspace: public
