version: v1
name: "bigquery"
type: depot
tags:
  - bigquery
layer: user
depot:
  type: BIGQUERY
  description: "Google Cloud BigQuery"
  spec:
    project: tmdc-demos
  external: true
  connectionSecret:
    - acl: rw
      type: key-value-properties
      files:
        json_keyfile: device-telemetry-production/common/depot/secret.json