name: postgres-secret
version: v1
type: instance-secret
description: secrets
layer: user
instance-secret:
  type: key-value-properties
  acl: rw
  data:
    user: customer-360-user
  files:
    credentials: customer-360/1.1-instance-secrets/secret.properties
