name: wf-customer-360-data-product-scanner
version: v1
type: workflow
description: |
  Scans and registers customer-360 consumer-aligned data products and semantic models into the data catalog.
workflow:
  dag:
    - name: customer-360-data-product-scanner
      description: |
        Scans the semantic model for customer-360 and registers it into the data catalog.
      title: customer-360 Data Product Scanner
      spec:
        stack: scanner:2.0
        compute: runnable-default
        runAsUser: metis
        stackSpec:
          type: semantic-model
          sourceConfig:
            config:
              type: SemanticModel
              markDeletedDataProducts: true
              dataProductFilterPattern:
                includes:
                  - customer-360
