name: customers-bundle
version: v1beta
type: bundle
tags:
  - Tier.Gold
description: The purpose of the bundle is to deploy the resources of the customers Data Product, making it available for consumption in customers.
layer: "user"
bundle:
  resources:
    - id: customers-pipeline
      file: customers/customers/deploy/pipeline.yaml
      workspace: public
