---
name: snowflake-r
version: v1
type: instance-secret
description: "The purpose of secret to mount the snowflake"
layer: user
instance-secret:
  type: key-value-properties
  acl: r
  data:
    username: 
    password: 
---
name: snowflake-rw
version: v1
type: instance-secret
description: "The purpose of secret to mount the snowflake"
layer: user
instance-secret:
  type: key-value-properties
  acl: rw
  data:
    username: 
    password: 