name: bigquery-automation-secret # Unique identifier for Resource, replace ${bigquery-depot-name} with depot name
version: v1 # Manifest version
type: instance-secret # Type of the Resource
description: secrets # Purpose of the Instance-secret
layer: user # DataOS layer
instance-secret:
  type: key-value-properties # Secret type
  acl: rw # Access control: 'r' for read-only
  data:
    projectid: tmdc-demos
    email: tmdc-engg@tmdc-demos.iam.gserviceaccount.com # Replace with Bigquery email ID
  files:
    json_keyfile: customer-market-place/1.1-instance-secrets/secret.json