name: customer-bundle
version: v1beta
type: bundle
tags:
  - Tier.Gold
description: The purpose of the bundle is to deploy the resources of the customer Data Product, making it available for consumption in customer.
layer: "user"
bundle:
  resources:
    - id: customer-pipeline
      file: 2.1-customer/deploy/pipeline.yaml
      workspace: public
